# Generated by Django 5.1.4 on 2025-01-01 05:29

import datetime
import django.db.models.deletion
import siwarkah.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kecamatan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=3, unique=True)),
                ('nama', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('departemen', models.CharField(max_length=100)),
                ('bidang', models.CharField(max_length=50)),
                ('create_date', models.DateTimeField(default=datetime.datetime.today)),
                ('update_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kelurahan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=6, unique=True)),
                ('nama', models.CharField(max_length=50)),
                ('kecamatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siwarkah.kecamatan')),
            ],
        ),
        migrations.CreateModel(
            name='Warkah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_subjek', models.CharField(max_length=128)),
                ('no_berkas', models.CharField(max_length=4)),
                ('tahun', models.IntegerField()),
                ('document', models.FileField(max_length=500, upload_to=siwarkah.models.upload_dest)),
                ('create_date', models.DateTimeField(default=datetime.datetime.today)),
                ('kecamatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siwarkah.kecamatan')),
                ('kelurahan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siwarkah.kelurahan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siwarkah.user')),
            ],
        ),
    ]
